-- MySQL Script generated by MySQL Workbench
-- Sat Nov 16 19:29:56 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gotokodb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gotokodb` ;

-- -----------------------------------------------------
-- Schema gotokodb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gotokodb` DEFAULT CHARACTER SET utf8mb4 ;
USE `gotokodb` ;

-- -----------------------------------------------------
-- Table `gotokodb`.`sections`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gotokodb`.`sections` ;

CREATE TABLE IF NOT EXISTS `gotokodb`.`sections` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gotokodb`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gotokodb`.`categories` ;

CREATE TABLE IF NOT EXISTS `gotokodb`.`categories` (
  `id` VARCHAR(36) NOT NULL,
  `parent_id` VARCHAR(36) NULL,
  `section_id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_categories_categories1_idx` (`parent_id` ASC) VISIBLE,
  INDEX `fk_categories_sections1_idx` (`section_id` ASC) VISIBLE,
  CONSTRAINT `fk_categories_categories1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `gotokodb`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categories_sections1`
    FOREIGN KEY (`section_id`)
    REFERENCES `gotokodb`.`sections` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gotokodb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gotokodb`.`users` ;

CREATE TABLE IF NOT EXISTS `gotokodb`.`users` (
  `id` VARCHAR(36) NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(255) NULL DEFAULT NULL,
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_email_unique` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gotokodb`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gotokodb`.`orders` ;

CREATE TABLE IF NOT EXISTS `gotokodb`.`orders` (
  `id` VARCHAR(36) NOT NULL,
  `user_id` VARCHAR(36) NOT NULL,
  `code` VARCHAR(255) NOT NULL,
  `status` VARCHAR(255) NOT NULL,
  `order_date` DATETIME NOT NULL,
  `payment_due` DATETIME NOT NULL,
  `payment_status` VARCHAR(255) NOT NULL,
  `payment_token` VARCHAR(255) NULL DEFAULT NULL,
  `payment_url` VARCHAR(255) NULL DEFAULT NULL,
  `base_total_price` DECIMAL(16,2) NOT NULL DEFAULT '0.00',
  `tax_amount` DECIMAL(16,2) NOT NULL DEFAULT '0.00',
  `tax_percent` DECIMAL(16,2) NOT NULL DEFAULT '0.00',
  `discount_amount` DECIMAL(16,2) NOT NULL DEFAULT '0.00',
  `discount_percent` DECIMAL(16,2) NOT NULL DEFAULT '0.00',
  `shipping_cost` DECIMAL(16,2) NOT NULL DEFAULT '0.00',
  `grand_total` DECIMAL(16,2) NOT NULL DEFAULT '0.00',
  `note` TEXT NULL DEFAULT NULL,
  `shipping_courier` VARCHAR(255) NULL DEFAULT NULL,
  `shipping_service_name` VARCHAR(255) NULL DEFAULT NULL,
  `approved_by` VARCHAR(36) NULL DEFAULT NULL,
  `approved_at` DATETIME NULL DEFAULT NULL,
  `cancelled_by` VARCHAR(36) NULL DEFAULT NULL,
  `cancelled_at` DATETIME NULL DEFAULT NULL,
  `cancellation_note` TEXT NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `orders_code_unique` (`code` ASC) VISIBLE,
  INDEX `orders_user_id_foreign` (`user_id` ASC) VISIBLE,
  INDEX `orders_approved_by_foreign` (`approved_by` ASC) VISIBLE,
  INDEX `orders_cancelled_by_foreign` (`cancelled_by` ASC) VISIBLE,
  INDEX `orders_code_index` (`code` ASC) VISIBLE,
  INDEX `orders_code_order_date_index` (`code` ASC, `order_date` ASC) VISIBLE,
  INDEX `orders_payment_token_index` (`payment_token` ASC) VISIBLE,
  CONSTRAINT `orders_approved_by_foreign`
    FOREIGN KEY (`approved_by`)
    REFERENCES `gotokodb`.`users` (`id`),
  CONSTRAINT `orders_cancelled_by_foreign`
    FOREIGN KEY (`cancelled_by`)
    REFERENCES `gotokodb`.`users` (`id`),
  CONSTRAINT `orders_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `gotokodb`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gotokodb`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gotokodb`.`products` ;

CREATE TABLE IF NOT EXISTS `gotokodb`.`products` (
  `id` VARCHAR(36) NOT NULL,
  `parent_id` VARCHAR(36) NULL DEFAULT NULL,
  `user_id` VARCHAR(36) NOT NULL,
  `sku` VARCHAR(255) NOT NULL,
  `type` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `price` DECIMAL(15,2) NULL DEFAULT NULL,
  `stock` INT NULL DEFAULT NULL,
  `weight` DECIMAL(10,2) NULL DEFAULT NULL,
  `short_description` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `description` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `status` INT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `products_user_id_foreign` (`user_id` ASC) VISIBLE,
  INDEX `products_parent_id_foreign` (`parent_id` ASC) VISIBLE,
  FULLTEXT INDEX `search` (`name`, `slug`, `short_description`, `description`) VISIBLE,
  CONSTRAINT `products_parent_id_foreign`
    FOREIGN KEY (`parent_id`)
    REFERENCES `gotokodb`.`products` (`id`),
  CONSTRAINT `products_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `gotokodb`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gotokodb`.`order_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gotokodb`.`order_items` ;

CREATE TABLE IF NOT EXISTS `gotokodb`.`order_items` (
  `id` VARCHAR(36) NOT NULL,
  `order_id` VARCHAR(36) NOT NULL,
  `product_id` VARCHAR(36) NOT NULL,
  `qty` INT NOT NULL,
  `base_price` DECIMAL(16,2) NOT NULL DEFAULT '0.00',
  `base_total` DECIMAL(16,2) NOT NULL DEFAULT '0.00',
  `tax_amount` DECIMAL(16,2) NOT NULL DEFAULT '0.00',
  `tax_percent` DECIMAL(16,2) NOT NULL DEFAULT '0.00',
  `discount_amount` DECIMAL(16,2) NOT NULL DEFAULT '0.00',
  `discount_percent` DECIMAL(16,2) NOT NULL DEFAULT '0.00',
  `sub_total` DECIMAL(16,2) NOT NULL DEFAULT '0.00',
  `sku` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `weight` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `order_items_order_id_foreign` (`order_id` ASC) VISIBLE,
  INDEX `order_items_product_id_foreign` (`product_id` ASC) VISIBLE,
  INDEX `order_items_sku_index` (`sku` ASC) VISIBLE,
  CONSTRAINT `order_items_order_id_foreign`
    FOREIGN KEY (`order_id`)
    REFERENCES `gotokodb`.`orders` (`id`),
  CONSTRAINT `order_items_product_id_foreign`
    FOREIGN KEY (`product_id`)
    REFERENCES `gotokodb`.`products` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gotokodb`.`payments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gotokodb`.`payments` ;

CREATE TABLE IF NOT EXISTS `gotokodb`.`payments` (
  `id` VARCHAR(36) NOT NULL,
  `order_id` VARCHAR(36) NOT NULL,
  `number` VARCHAR(255) NOT NULL,
  `amount` DECIMAL(16,2) NOT NULL DEFAULT '0.00',
  `method` VARCHAR(255) NOT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  `token` VARCHAR(255) NULL DEFAULT NULL,
  `payloads` JSON NULL DEFAULT NULL,
  `payment_type` VARCHAR(255) NULL DEFAULT NULL,
  `va_number` VARCHAR(255) NULL DEFAULT NULL,
  `vendor_name` VARCHAR(255) NULL DEFAULT NULL,
  `biller_code` VARCHAR(255) NULL DEFAULT NULL,
  `bill_key` VARCHAR(255) NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `payments_number_unique` (`number` ASC) VISIBLE,
  INDEX `payments_order_id_foreign` (`order_id` ASC) VISIBLE,
  INDEX `payments_number_index` (`number` ASC) VISIBLE,
  INDEX `payments_method_index` (`method` ASC) VISIBLE,
  INDEX `payments_token_index` (`token` ASC) VISIBLE,
  INDEX `payments_payment_type_index` (`payment_type` ASC) VISIBLE,
  CONSTRAINT `payments_order_id_foreign`
    FOREIGN KEY (`order_id`)
    REFERENCES `gotokodb`.`orders` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gotokodb`.`product_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gotokodb`.`product_categories` ;

CREATE TABLE IF NOT EXISTS `gotokodb`.`product_categories` (
  `id` VARCHAR(36) NOT NULL,
  `product_id` VARCHAR(36) NOT NULL,
  `category_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `product_categories_product_id_foreign` (`product_id` ASC) VISIBLE,
  INDEX `product_categories_category_id_foreign` (`category_id` ASC) VISIBLE,
  CONSTRAINT `product_categories_category_id_foreign`
    FOREIGN KEY (`category_id`)
    REFERENCES `gotokodb`.`categories` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `product_categories_product_id_foreign`
    FOREIGN KEY (`product_id`)
    REFERENCES `gotokodb`.`products` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gotokodb`.`product_images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gotokodb`.`product_images` ;

CREATE TABLE IF NOT EXISTS `gotokodb`.`product_images` (
  `id` VARCHAR(36) NOT NULL,
  `product_id` VARCHAR(36) NOT NULL,
  `path` TEXT NOT NULL,
  `extra_large` VARCHAR(255) NULL DEFAULT NULL,
  `large` VARCHAR(255) NULL DEFAULT NULL,
  `medium` VARCHAR(255) NULL DEFAULT NULL,
  `small` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `product_images_product_id_foreign` (`product_id` ASC) VISIBLE,
  CONSTRAINT `product_images_product_id_foreign`
    FOREIGN KEY (`product_id`)
    REFERENCES `gotokodb`.`products` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gotokodb`.`shipments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gotokodb`.`shipments` ;

CREATE TABLE IF NOT EXISTS `gotokodb`.`shipments` (
  `id` VARCHAR(36) NOT NULL,
  `user_id` VARCHAR(36) NOT NULL,
  `order_id` VARCHAR(36) NOT NULL,
  `track_number` VARCHAR(255) NULL DEFAULT NULL,
  `status` VARCHAR(255) NOT NULL,
  `total_qty` INT NOT NULL,
  `total_weight` INT NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `address1` VARCHAR(255) NULL DEFAULT NULL,
  `address2` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `city_id` VARCHAR(255) NULL DEFAULT NULL,
  `province_id` VARCHAR(255) NULL DEFAULT NULL,
  `postcode` INT NULL DEFAULT NULL,
  `shipped_by` VARCHAR(36) NULL DEFAULT NULL,
  `shipped_at` DATETIME NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `shipments_user_id_foreign` (`user_id` ASC) VISIBLE,
  INDEX `shipments_order_id_foreign` (`order_id` ASC) VISIBLE,
  INDEX `shipments_shipped_by_foreign` (`shipped_by` ASC) VISIBLE,
  INDEX `shipments_track_number_index` (`track_number` ASC) VISIBLE,
  CONSTRAINT `shipments_order_id_foreign`
    FOREIGN KEY (`order_id`)
    REFERENCES `gotokodb`.`orders` (`id`),
  CONSTRAINT `shipments_shipped_by_foreign`
    FOREIGN KEY (`shipped_by`)
    REFERENCES `gotokodb`.`users` (`id`),
  CONSTRAINT `shipments_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `gotokodb`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gotokodb`.`order_customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gotokodb`.`order_customers` ;

CREATE TABLE IF NOT EXISTS `gotokodb`.`order_customers` (
  `id` VARCHAR(36) NOT NULL,
  `user_id` VARCHAR(36) NOT NULL,
  `order_id` VARCHAR(36) NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `address1` VARCHAR(255) NULL DEFAULT NULL,
  `address2` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `city_id` VARCHAR(255) NULL DEFAULT NULL,
  `province_id` VARCHAR(255) NULL DEFAULT NULL,
  `postcode` INT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `shipments_user_id_foreign` (`user_id` ASC) VISIBLE,
  INDEX `shipments_order_id_foreign` (`order_id` ASC) VISIBLE,
  CONSTRAINT `shipments_order_id_foreign0`
    FOREIGN KEY (`order_id`)
    REFERENCES `gotokodb`.`orders` (`id`),
  CONSTRAINT `shipments_user_id_foreign0`
    FOREIGN KEY (`user_id`)
    REFERENCES `gotokodb`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gotokodb`.`addresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gotokodb`.`addresses` ;

CREATE TABLE IF NOT EXISTS `gotokodb`.`addresses` (
  `id` VARCHAR(36) NOT NULL,
  `user_id` VARCHAR(36) NULL,
  `name` VARCHAR(255) NOT NULL,
  `address1` VARCHAR(255) NULL DEFAULT NULL,
  `address2` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `city_id` VARCHAR(255) NULL DEFAULT NULL,
  `province_id` VARCHAR(255) NULL DEFAULT NULL,
  `postcode` INT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `shipments_user_id_foreign` (`user_id` ASC) VISIBLE,
  CONSTRAINT `shipments_user_id_foreign00`
    FOREIGN KEY (`user_id`)
    REFERENCES `gotokodb`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
